
export const INSERT = "INSERT";
export const INSERT_PENDING = "INSERT_PENDING";
export const INSERT_FULFILLED = "INSERT_FULFILLED";
export const INSERT_REJECTED = "INSERT_REJECTED";

export const FETCH = "FETCH";
export const FETCH_PENDING = "FETCH_PENDING";
export const FETCH_FULFILLED = "FETCH_FULFILLED";
export const FETCH_REJECTED = "FETCH_REJECTED";
